# 국민청원 텍스트 분류 프로젝트

## 01. 데이터 다운로드 및 패키지 설치

In [1]:
!pip install konlpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 50.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.6/488.6 kB 22.5 MB/s eta 0:00:00


In [2]:
!pip install torchtext==0.6.0

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.2/64.2 kB 5.6 MB/s eta 0:00:00


In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
!pwd

/content


In [6]:
!unzip "/content/drive/MyDrive/Colab Notebooks/AIsystem4weeks/crawling.zip" -d "/content/drive/MyDrive/Colab Notebooks/AIsystem4weeks/dataset/"

Archive:  /content/drive/MyDrive/Colab Notebooks/AIsystem4weeks/crawling.zip
  inflating: /content/drive/MyDrive/Colab Notebooks/AIsystem4weeks/dataset/crawling.csv  


In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/AIsystem4weeks/dataset/crawling.csv")

In [9]:
df.loc[0].content

'본인은 2019년 8월 경 서울지방병무청 제1검사장 탈의실에서 믿을 수 없는 것을 발견하였다. 탈의실 천장에 CCTV를 발견한 것이다. 본인은 이에 경악하였다.\r\n\r\r\n탈의실에 CCTV를 설치하는 것은 개인정보보호법 25조 2항을 위반한 사안으로 심각한 법적 문제이다. 촬영이 되었다면 이는 성폭력범죄의 처벌 등에 관한 특례법 14조 1항 위반이기도 하다. 또한, 법적인 문제일 뿐만 아니라 개인의 자유를 침해하고 성적 수치심을 불러일으키는 매우 심각한 윤리적 문제이다.\r\r\n이렇듯 불법카메라는 그 자체로 굉장히 심각한 문제이다. 그런데 공공기관에서 탈의실에 불법, 비윤리적으로 카메라를 설치하였고, 이를 운영하였을지도 모르는 상황이 발생하였다. 도대체 한국 정부는 인권을 무엇이라고 생각하는 것인가? \r\n\r\r\n발견 직후 인권위에 진정을 넣었지만 인권위에서는 현재까지 조사가 되고 있는지, 진행은 어떻게 되었는지 어떠한 답변도 하지 않고 있다. 병무청측에서도 어떠한 답변도 없었다.\r\n\r\r\n더 이상 답변을 기다리는 것이 의미 없다고 생각한 본인은 모 커뮤니티에 이 사실을 알렸다. 이후 이슈화가 되자 병무청은 설치는 되었으나 운영은 하지 않았다는 대답을 내놓았지만 이에 대한 조사 경과 발표나 사과, 책임 있는 대응은 전혀 보여주고 있지 않다.\r\n\r\r\n이는 개인의 자유와 권리의 본질적 내용을 침해하는 강제징집, 국제노동기구가 인정한 강제징용/강제노동을 당하는 20대 남성들이 국가에 의해 신체를 감시당한 사건이다. 한국 정부는 병역의무자에게는 인권이 없다고 생각하는가?\r\n\r\r\n언제까지 국가는 개인들을 노예 취급할 것인가? 몇백원도 안되는 시급을 주며 강제로 폭력 속에서 부리는 것도 모자라 이제는 이런 어처구니 없는 일까지 일어나는 것에 경악하지 않을 수 없다. \r\n\r\r\n이에 본인은 위 사실을 강력히 규탄하며 아래와 같은 대응을 요구한다.\r\n\r\r\n1. 서울지방병무청 징병검사소 탈의실에 CCTV가 설치된 경위와 

In [18]:
import re

def remove_white_space(text):
    text = re.sub(r'[\t\r\n\f\v]', ' ', str(text))
    return text

def remove_special_char(text):
    text = re.sub('[^ ㄱ-ㅣ가-힣 0-9]+', ' ', str(text))
    return text

df.title = df.title.apply(remove_white_space)
df.title = df.title.apply(remove_special_char)

df.content = df.content.apply(remove_white_space)
df.content = df.content.apply(remove_special_char)

In [22]:
df.loc[3].content

'미세먼지의 심각성은 이제 적극적인 대안을 요구 하고 있습니다    우리 일상에서 가장 쉽고 적극적으로 할 수 있는 것은 모든 건축물 외부에 스프링쿨러를 설치하는 것입니다     도로변에도 가로등 등을 이용하여 스프링쿨러를 설치하여 일정 농도이상의 미세먼지 발생시 물을 뿌리면 즉시 미세먼지를 흡착 줄일 수 있습니다    특히 옥상조경 혹은 건물외부 수직정원 등과 결합한다면 환경문제를 적극적으로 해결할 수 있습니다    더운 여름에는 10도이상의 온도를 낮출 수 있고   겨울에는 미세먼지 뿐만아니라 도시의 온도를 10도 이상 올릴 수도 있습니다    그리고 각 가정마다 각 건물마다 수도 시설이 갖추어져 옥외 스프링쿨러 설치 비용은 최소 몇만원 최대로 하더라도 100만원을 넘지 않는 저예산이지만 효과는 즉시 나타날 수 있습니다    옥상녹화화 수직정원이 결합된다면 금수강산의 대한민국을 다시 만들 수 있습니다    감사합니다    참고로 저는 농업인이며 농생물학 원예생태시스템공학을 전공 박사학위 소유자 이며 현제 수직정원과 인공구조물 녹화 그리고 식물신품종 개발로 해외 로열티를 수출하고 있으며 정원관련분야의 일도하고 있습니다    미세먼지와 도시 환경문제의 근본적 대책은 매우 많은 시간과 노력이 필요한 것 입니다만 우선 적극적임 대안 중 가장 실효성있는 대안 이니 적극 검토 바랍니다 '

## 2.3 Tokenizer 생성

In [20]:
from konlpy.tag import Okt
okt = Okt()

In [45]:
okt.morphs(df.loc[3].content)

['미세먼지',
 '의',
 '심각',
 '성은',
 '이제',
 '적극',
 '적',
 '인',
 '대안',
 '을',
 '요구',
 '하고',
 '있습니다',
 '우리',
 '일상',
 '에서',
 '가장',
 '쉽고',
 '적극',
 '적',
 '으로',
 '할',
 '수',
 '있는',
 '것',
 '은',
 '모든',
 '건축물',
 '외부',
 '에',
 '스프링',
 '쿨러',
 '를',
 '설치',
 '하는',
 '것',
 '입니다',
 '도로',
 '변',
 '에도',
 '가로등',
 '등',
 '을',
 '이용',
 '하여',
 '스프링',
 '쿨러',
 '를',
 '설치',
 '하여',
 '일정',
 '농도',
 '이상',
 '의',
 '미세먼지',
 '발생',
 '시',
 '물',
 '을',
 '뿌리',
 '면',
 '즉시',
 '미세먼지',
 '를',
 '흡착',
 '줄일',
 '수',
 '있습니다',
 '특히',
 '옥상',
 '조경',
 '혹은',
 '건물',
 '외부',
 '수직',
 '정원',
 '등',
 '과',
 '결합',
 '한',
 '다',
 '면',
 '환경문제',
 '를',
 '적극',
 '적',
 '으로',
 '해결',
 '할',
 '수',
 '있습니다',
 '더운',
 '여름',
 '에는',
 '10',
 '도',
 '이상',
 '의',
 '온도',
 '를',
 '낮출',
 '수',
 '있고',
 '겨울',
 '에는',
 '미세먼지',
 '뿐',
 '만',
 '아니라',
 '도시',
 '의',
 '온도',
 '를',
 '10',
 '도',
 '이상',
 '올릴',
 '수도',
 '있습니다',
 '그리고',
 '각',
 '가정',
 '마다',
 '각',
 '건물',
 '마다',
 '수도',
 '시설',
 '이',
 '갖추어져',
 '옥외',
 '스프링',
 '쿨러',
 '설치',
 '비용',
 '은',
 '최소',
 '몇',
 '만원',
 '최대로',
 '하더라도',
 '100만원',
 '을',
 '넘지',
 '않는'

In [23]:
df["title_token"] = df.title.apply(okt.morphs)

In [25]:
df["content_token"] = df.content.apply(okt.morphs)

In [28]:
df['count'] = df['count'].replace({',' : ''}, regex = True).apply(lambda x : int(x))

In [29]:
df["label"] = df["count"].apply(lambda x: "Yes" if int(x) > 1000 else "No")

In [30]:
df["token_final"] = df.title_token + df.content_token

In [32]:
df.to_csv("/content/drive/MyDrive/Colab Notebooks/AIsystem4weeks/dataset/df.csv", index=False, encoding="utf-8-sig")

In [33]:
df_new = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/AIsystem4weeks/dataset/df.csv")

## 2.4 단어 벡터 학습

In [34]:
from gensim.models import Word2Vec

In [46]:
df_drop = df[["token_final", "label"]]

In [48]:
embedding_model = Word2Vec(df_drop['token_final'],
                           sg = 1, # skip-gram
                           vector_size = 100,
                           window = 2,
                           min_count = 1,
                           workers = 4
                           )


In [49]:
embedding_model.wv.most_similar("음주운전")

[('음주', 0.8254624009132385),
 ('뺑소니', 0.7772663235664368),
 ('가정폭력', 0.75697922706604),
 ('무면허', 0.752689778804779),
 ('동물학대', 0.731476366519928),
 ('강력범죄', 0.7251717448234558),
 ('경미한', 0.7231563329696655),
 ('스토킹', 0.7143633961677551),
 ('범의', 0.7114167213439941),
 ('촉법소년', 0.7090577483177185)]

In [50]:
embedding_model.wv.save_word2vec_format("/content/drive/MyDrive/Colab Notebooks/AIsystem4weeks/dataset/word2vec_100")

## 2.5. 학습데이터 분리 및 전처리

In [51]:
from numpy.random import RandomState

rng = RandomState()

tr = df_drop.sample(frac=0.8, random_state=rng)
val = df_drop.loc[~df_drop.index.isin(tr.index)]

tr.to_csv('/content/drive/MyDrive/Colab Notebooks/AIsystem4weeks/dataset/train.csv', index=False, encoding='utf-8-sig')
val.to_csv('/content/drive/MyDrive/Colab Notebooks/AIsystem4weeks/dataset/validation.csv', index=False, encoding='utf-8-sig')

In [52]:
from torchtext.data import Field, TabularDataset, BucketIterator

In [53]:

def tokenizer(text):
  text = re.sub('[\[\]\']', '', str(text))
  text = text.split(', ')
  return text


TEXT = Field(tokenize=tokenizer)
LABEL = Field(sequential=False)

In [54]:
train, validation = TabularDataset.splits(
    path = '/content/drive/MyDrive/Colab Notebooks/AIsystem4weeks/dataset/',
    train = 'train.csv',
    validation = 'validation.csv',
    format = 'csv',
    fields = [('text', TEXT), ('label', LABEL)],
    skip_header = True
)

In [59]:
from torchtext.vocab import Vectors

In [60]:
vectors = Vectors(name="/content/drive/MyDrive/Colab Notebooks/AIsystem4weeks/dataset/word2vec_100")

100%|██████████| 115919/115919 [00:05<00:00, 20539.90it/s]


In [65]:
vectors.get_vecs_by_tokens(["음주운전", "경찰"])

tensor([[-3.0596e-02,  5.8809e-02,  1.0217e-01, -4.1449e-01, -4.8435e-01,
          5.4148e-02, -1.5849e-01,  1.4152e+00,  3.5276e-01, -3.3121e-01,
         -1.3515e-01, -7.0695e-01, -5.0184e-01,  1.2130e-01,  7.0898e-02,
         -2.9134e-01, -1.5452e-01,  2.4210e-02, -3.4748e-03, -6.9410e-01,
         -3.0257e-03, -6.7591e-01,  8.5639e-01, -2.7614e-01, -4.8158e-01,
          4.3820e-02, -2.6797e-01, -4.2378e-03, -5.0938e-01, -2.0197e-01,
          3.5371e-01,  1.1296e-05,  2.1175e-01, -1.2008e-01,  2.6784e-01,
          2.1964e-01, -8.6971e-02,  4.9958e-01, -2.6111e-01, -5.0778e-01,
          5.6902e-01, -7.8566e-01,  1.0733e-01,  2.0490e-01, -1.4446e-01,
         -1.0831e-01,  5.0617e-01,  8.3595e-02,  1.2499e-01,  4.9239e-01,
          5.2657e-01, -2.4698e-01,  2.1540e-01, -2.4402e-01, -3.6921e-01,
          2.8699e-01, -3.9311e-01,  1.1659e-01, -2.5250e-01,  3.3678e-02,
          1.0127e-01, -3.1566e-02,  2.1445e-01,  1.6711e-01,  1.8432e-01,
          4.5654e-01, -3.6160e-01,  5.

In [66]:
TEXT.build_vocab(train, vectors = vectors, min_freq = 1, max_size = None)
LABEL.build_vocab(train)

In [68]:
import torch

In [69]:
vocab = TEXT.vocab

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

train_iter, validation_iter = BucketIterator.splits(
    datasets = (train, validation),
    batch_size = 8,
    device = device,
    sort = False
)

print('임베딩 벡터의 개수와 차원 : {} '.format(TEXT.vocab.vectors.shape))

임베딩 벡터의 개수와 차원 : torch.Size([104034, 100]) 


## 3. 모델 구현

In [74]:
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [86]:
embed = nn.Embedding(len(TEXT.vocab), 100)

In [87]:
print(embed)
print(embed.weight[2])

Embedding(104034, 100)
tensor([ 1.3509,  0.3045, -0.7341, -0.7933,  1.9243, -1.0441, -0.0917, -0.1500,
        -1.9778,  0.1743, -1.2043, -1.0877,  1.3057,  0.7750, -0.5772,  0.2646,
        -0.9794, -0.3104, -1.2105, -1.4194,  0.8624, -1.1075, -0.5825,  0.6018,
         1.5183, -1.6114, -2.0476,  0.5182, -0.2402,  0.4167,  1.1656, -0.6891,
        -1.0914,  0.3510,  0.3698, -0.5992, -2.3133,  0.3248,  0.5144,  0.5214,
         1.0274,  0.3741, -0.5552, -0.8392,  1.2387,  0.2794, -0.2842, -0.4919,
         1.2812, -1.2471,  0.4673,  0.1814,  0.7056, -1.0924, -0.3298,  0.1920,
         0.9029, -0.3833,  1.1108,  0.2403, -1.9957,  0.3415,  0.3656,  0.6358,
         1.8032, -0.4181, -2.4623,  1.5435,  0.1219, -0.2196,  0.1111, -0.4748,
        -0.5690,  0.4775,  1.0909,  0.2224,  0.0575,  0.0960,  0.6253, -1.4551,
        -0.3264,  0.4419,  0.7499, -0.0381, -1.0664, -2.5035,  1.3299, -1.0836,
        -0.6953,  0.8625,  0.0165,  1.6797,  1.6554,  0.5479, -0.9214,  1.3186,
        -0.3880, 

In [88]:
embed.weight.data.copy_(TEXT.vocab.vectors)

tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-0.2237,  0.0882, -0.0217,  ..., -0.3458, -0.1756, -0.0120],
        ...,
        [-0.1848,  0.0219,  0.0629,  ..., -0.1272,  0.0245,  0.0274],
        [-0.0649, -0.0121,  0.0216,  ..., -0.0696, -0.0070,  0.0285],
        [-0.0536,  0.0065,  0.0472,  ..., -0.0387,  0.0218,  0.0392]])

In [92]:
print(embed.weight[2])

tensor([-0.2237,  0.0882, -0.0217,  0.3620, -0.1883, -0.5353,  0.2950,  0.2727,
        -0.3858, -0.0290,  0.3661, -0.2263, -0.2031,  0.4768, -0.4138,  0.1610,
         0.1333, -0.0555, -0.5223, -0.7141,  0.2828, -0.0300,  0.2580, -0.8550,
         0.3206,  0.1159, -0.2475,  0.6952, -0.7007,  0.4251, -0.2368, -0.0618,
         0.1098, -0.5300,  0.1946, -0.1865,  0.2140, -0.0113,  0.0546, -0.3591,
        -0.4690, -0.3867, -0.3845,  0.0550, -0.1183,  0.3102, -0.2602, -0.0485,
         0.0821,  0.5667,  0.0355,  0.3349, -0.1392, -0.4816,  0.4625,  0.2882,
        -0.0167,  0.4206,  0.0899, -0.0100,  0.2468, -0.0123, -0.1678, -0.4487,
        -0.2854,  0.1727, -0.5750,  0.2016, -0.0531,  0.9929,  0.3119,  0.7118,
        -0.0320, -0.0949,  1.2920, -0.3011,  0.4981, -0.0450, -0.0760, -0.5450,
        -0.4805, -0.1739,  0.4140,  0.8735, -0.2054,  0.0183,  0.3496, -0.2620,
         0.0677,  0.6475, -0.2792, -0.6427, -0.0098,  0.1152,  0.3429,  0.0333,
         0.0735, -0.3458, -0.1756, -0.01

In [93]:
conv1 = nn.Conv2d(in_channels = 1,
          out_channels = 10,
          kernel_size = (3, 100))

In [108]:
for batch in train_iter:
  #print(batch.text)
  #print(batch.text.size())
  text, target = batch.text, batch.label
  text = text.to(device)
  target = target.to(device)
  print(text)
  print(target)
  embed = embed.to(device)
  embed_text = embed(text)
  print(embed_text.size())
  #embed_text = embed_text.view(8,-1, 100)
  #print(embed_text.size())
  embed_text = embed_text.unsqueeze(1)
  print(embed_text.size())
  conv1 = conv1.to(device)
  conv1(embed_text)
  #embed_text = embed_text.unsqueeze(1)
  #print(embed_text.size())

  break

tensor([[   53,    10,   102,  ..., 13162,   346,  5286],
        [    5,   596,     9,  ...,     5,  1679,     4],
        [  235, 11368,  1260,  ..., 12277,  1911,  2078],
        ...,
        [    1,   200,     1,  ...,     1,     1,     1],
        [    1,   225,     1,  ...,     1,     1,     1],
        [    1,    76,     1,  ...,     1,     1,     1]], device='cuda:0')
tensor([2, 1, 2, 2, 1, 1, 2, 2], device='cuda:0')
torch.Size([896, 8, 100])
torch.Size([896, 1, 8, 100])


In [95]:
conv1(embed(torch.tensor([2, 3])))

RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [2, 100]